"""add schedule_fixtures table and fixture_loans schedule_id

Revision ID: 3dc9bb30d51f
Revises: 26d9a0677843
Create Date: 2026-03-29 06:15:54.181610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc9bb30d51f'
down_revision: Union[str, Sequence[str], None] = '26d9a0677843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_fixtures_fixture_id'), 'schedule_fixtures', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_schedule_fixtures_id'), 'schedule_fixtures', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_fixtures_schedule_id'), 'schedule_fixtures', ['schedule_id'], unique=False)
    op.add_column('fixture_loans', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fixture_loans_schedule_id'), 'fixture_loans', ['schedule_id'], unique=False)
    # SQLite 不支援 ALTER TABLE ADD CONSTRAINT，用 batch mode 重建表以加入 FK
    with op.batch_alter_table('fixture_loans') as batch_op:
        batch_op.create_foreign_key('fk_fixture_loans_schedule_id', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixture_loans') as batch_op:
        batch_op.drop_constraint('fk_fixture_loans_schedule_id', type_='foreignkey')
    op.drop_index(op.f('ix_fixture_loans_schedule_id'), table_name='fixture_loans')
    op.drop_column('fixture_loans', 'schedule_id')
    op.drop_index(op.f('ix_schedule_fixtures_schedule_id'), table_name='schedule_fixtures')
    op.drop_index(op.f('ix_schedule_fixtures_id'), table_name='schedule_fixtures')
    op.drop_index(op.f('ix_schedule_fixtures_fixture_id'), table_name='schedule_fixtures')
    op.drop_table('schedule_fixtures')
    # ### end Alembic commands ###
