"""drop line_bind_requests and notification_failures

Revision ID: 97789ba91e84
Revises: 3dc9bb30d51f
Create Date: 2026-04-03 07:12:08.134189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97789ba91e84'
down_revision: Union[str, Sequence[str], None] = '3dc9bb30d51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_bind_requests_id'), table_name='line_bind_requests')
    op.drop_index(op.f('ix_line_bind_requests_line_user_id'), table_name='line_bind_requests')
    op.drop_index(op.f('ix_line_bind_requests_status'), table_name='line_bind_requests')
    op.drop_table('line_bind_requests')
    op.drop_index(op.f('ix_notification_failures_id'), table_name='notification_failures')
    op.drop_table('notification_failures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_failures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('notif_type', sa.VARCHAR(), nullable=False),
    sa.Column('target', sa.VARCHAR(), nullable=True),
    sa.Column('message_preview', sa.VARCHAR(), nullable=True),
    sa.Column('error_msg', sa.TEXT(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_failures_id'), 'notification_failures', ['id'], unique=False)
    op.create_table('line_bind_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('line_user_id', sa.VARCHAR(), nullable=False),
    sa.Column('requested_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('matched_user_id', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_bind_requests_status'), 'line_bind_requests', ['status'], unique=False)
    op.create_index(op.f('ix_line_bind_requests_line_user_id'), 'line_bind_requests', ['line_user_id'], unique=False)
    op.create_index(op.f('ix_line_bind_requests_id'), 'line_bind_requests', ['id'], unique=False)
    # ### end Alembic commands ###
