"""add composite index device_data device_id timestamp

Revision ID: cdd650ed8d87
Revises: a517a1796fda
Create Date: 2026-03-15 22:51:14.548947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd650ed8d87'
down_revision: Union[str, Sequence[str], None] = 'a517a1796fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_device_data_device_timestamp', 'device_data', ['device_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_data_device_timestamp', table_name='device_data')
    # ### end Alembic commands ###
