"""
DNV 船舶設備環境認證標準
- DNVGL-CG-0339:2015（現行，Class A/B/C/D）
- DNV Std.Cert.2.4（舊版）

ramp_rate：✅ DNVGL-CG-0339 Sec.3 [7][9] 明文：1°C/min
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "DNV 船舶設備環境認證",
    "description": "DNV（Det Norske Veritas）船舶自動化儀器設備認證。依船上安裝位置分 Class A/B/C/D。容差：溫度 ±2°C，濕度 ±10%RH。",
    "versions": {
        "DNVGL-CG-0339:2015": {
            "label": "DNVGL-CG-0339:2015（現行版）",
            "description": "現行版（2015年）。Class A/B：乾熱為主，冷測可選。Class C/D：乾熱 + 冷測均強制要求。容差：溫度 ±2°C，濕度 ±10%RH。",
            "tests": {
                "ClassA_Dry_Heat": {
                    "sop_id": "dnv_cg0339_classa_dry",
                    "name": "Class A 乾熱：+55°C，16h（機艙/控制室）",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class A：機艙、控制室、住艙等有溫度控制的室內環境（環境溫度 0°C ~ +45°C）。乾熱測試 +55°C，冷測可選不強制。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class A Sec.3[7]",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "ClassA_Damp_Heat": {
                    "sop_id": "dnv_cg0339_classa_damp",
                    "name": "Class A 濕熱（穩態）：+40°C，93%RH，4 天",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class A 濕熱：穩態濕熱（非循環），+40°C，93%RH，持續 96 小時（4 天）。依 IEC 60068-2-78 Test Cab 執行，通電工作狀態。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 96,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "DNVGL-CG-0339:2015 Sec.3[8.2] + IEC 60068-2-78 Test Cab",
                    "steps": steps_single_temp(40.0, 96, "high"),
                },
                "ClassB_Dry_Heat": {
                    "sop_id": "dnv_cg0339_classb_dry",
                    "name": "Class B 乾熱：+70°C，16h（箱體內部，temp rise ≥5°C）",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class B：箱體內部、桌面等溫升 ≥5°C 的位置（環境溫度 0°C ~ +55°C）。乾熱 +70°C，冷測不強制。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class B Sec.3[7]",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "ClassB_Damp_Heat_Cyclic": {
                    "sop_id": "dnv_cg0339_classb_damp",
                    "name": "Class B 濕熱循環：25°C ↔ 55°C，95%RH，2 循環",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class B 濕熱循環（結露），依 IEC 60068-2-30 Test Db 執行，2 循環，第一循環通電。",
                    "high_temperature": 55.0,
                    "low_temperature": 25.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 2.0,  # ⚠️ IEC 60068-2-30 程序控制（3h升溫），非獨立速率
                    "dwell_time_hours": 12,
                    "cycles": 2,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Sec.3[8.3] + IEC 60068-2-30 Test Db",
                    "steps": steps_cycle(25.0, 55.0, 2, 95.0),
                },
                "ClassC_Dry_Heat": {
                    "sop_id": "dnv_cg0339_classc_dry",
                    "name": "Class C 乾熱：+55°C，16h（無加熱遮蔽位置）【強制】",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class C：泵室、無加熱遮蔽位置（環境溫度 -25°C ~ +45°C）。乾熱 +55°C 強制，冷測 -25°C 強制。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class C Sec.3[7]（強制）",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "ClassC_Cold": {
                    "sop_id": "dnv_cg0339_classc_cold",
                    "name": "Class C 冷測：-25°C，2h（無加熱遮蔽位置）【強制】",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class C 冷測為強制項目。依法規 Sec.3 [9.2.4]，測試時間為 2 小時（test interval = 2 hours）。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class C Sec.3[9]（強制）",
                    "steps": steps_single_temp(-25.0, 2, "low"),
                },
                "ClassD_Dry_Heat": {
                    "sop_id": "dnv_cg0339_classd_dry",
                    "name": "Class D 乾熱：+70°C，16h（露天甲板）【強制】",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class D：露天甲板、桅杆等直接暴露天候位置（環境溫度 -25°C ~ +55°C）。乾熱 +70°C + 冷測 -25°C 均強制。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class D Sec.3[7]（強制）",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "ClassD_Cold": {
                    "sop_id": "dnv_cg0339_classd_cold",
                    "name": "Class D 冷測：-25°C，2h（露天甲板）【強制】",
                    "test_type": "chamber",
                    "version": "DNVGL-CG-0339:2015",
                    "description": "Class D 冷測強制項目，-25°C，測試時間 2 小時。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNVGL-CG-0339:2015 Table 2 Class D Sec.3[9]（強制）",
                    "steps": steps_single_temp(-25.0, 2, "low"),
                },
            },
        },
        "DNV Std.Cert.2.4": {
            "label": "DNV Std.Cert.2.4（舊版，仍廣泛使用）",
            "description": "舊版 DNV 2.4 認證，許多現有設備仍持此版認證。",
            "tests": {
                "ClassA_Dry_Heat": {
                    "sop_id": "dnv_24_classa_dry",
                    "name": "Class A 乾熱：+55°C，16h（機艙/控制室）",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class A 乾熱，+55°C。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.7 Class A",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "ClassB_Dry_Heat": {
                    "sop_id": "dnv_24_classb_dry",
                    "name": "Class B 乾熱：+70°C，16h（箱體內部）",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class B 乾熱，+70°C。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.7 Class B",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "ClassC_Dry_Heat": {
                    "sop_id": "dnv_24_classc_dry",
                    "name": "Class C 乾熱：+55°C，16h【強制】",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class C 乾熱，+55°C 強制。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.7 Class C",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "ClassC_Cold": {
                    "sop_id": "dnv_24_classc_cold",
                    "name": "Class C 冷測：-25°C，2h【強制】",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class C 冷測，-25°C 強制，2 小時。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.9 Class C",
                    "steps": steps_single_temp(-25.0, 2, "low"),
                },
                "ClassD_Dry_Heat": {
                    "sop_id": "dnv_24_classd_dry",
                    "name": "Class D 乾熱：+70°C，16h【強制】",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class D 乾熱，+70°C 強制。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.7 Class D",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "ClassD_Cold": {
                    "sop_id": "dnv_24_classd_cold",
                    "name": "Class D 冷測：-25°C，2h【強制】",
                    "test_type": "chamber",
                    "version": "DNV Std.Cert.2.4",
                    "description": "舊版 DNV 2.4 Class D 冷測，-25°C 強制，2 小時。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 10.0,
                    "reference": "DNV Std.Cert.2.4 Section 3.9 Class D",
                    "steps": steps_single_temp(-25.0, 2, "low"),
                },
            },
        },
    },
}
