"""
EN 50155 歐洲鐵路電子設備標準
- EN 50155:2017（現行，OT1~OT6 + ST1 + RTV + 濕熱循環）
- EN 50155:2007（舊版，T1/T2/T3/TX）

ramp_rate：✅ 法規曲線圖明文：1°C/min
RTV：✅ 法規明文：≥20°C/min

OT4 通電測試說明：
  - 升溫 + 三段電壓（×0.7 / operating / ×1.25）各 2h + 降溫 ≈ 法規參考 8h
  - dwell_time_hours = 2（單一電壓步驟停留時間）
  - ST1 延伸條件（OT4+15°C = 85°C）獨立一條
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "EN 50155 歐洲鐵路電子設備",
    "description": "適用於安裝在鐵路車輛上的電子設備。2017 版引入 OT1~OT6 六個溫度等級，取代 2007 版的 T1/T2/T3/TX。",
    "versions": {
        "EN 50155:2017": {
            "label": "EN 50155:2017（現行版）",
            "description": "現行版本。六個 OT 操作溫度等級，預設 OT3（-25°C ~ +70°C）。新增 Rapid Temperature Variation 測試。",
            "tests": {
                "OT1_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot1_high",
                    "name": "OT1 高溫乾熱：+55°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT1 等級（乘客車廂/駕駛室）。高溫上限 +55°C，持續 16 小時，非通電。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT1",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "OT1_Low_Cold": {
                    "sop_id": "en50155_2017_ot1_low",
                    "name": "OT1 低溫冷測：-25°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT1 等級低溫。以 IEC 60068-2-1 Test Ab 方法執行，-25°C 持續 16 小時。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT1 + IEC 60068-2-1",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
                "OT2_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot2_high",
                    "name": "OT2 高溫乾熱：+55°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT2 等級高溫上限同 OT1（+55°C），但低溫更嚴苛（-40°C）。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT2",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "OT2_Low_Cold": {
                    "sop_id": "en50155_2017_ot2_low",
                    "name": "OT2 低溫冷測：-40°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT2 等級低溫。-40°C 持續 16 小時，適用於極端氣候地區的鐵路設備。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT2 + IEC 60068-2-1",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "OT3_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot3_high",
                    "name": "OT3 高溫乾熱：+70°C，16h（非通電）【預設等級】",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT3 為 EN 50155:2017 預設等級。高溫 +70°C 持續 16 小時，適用於大多數鐵路車載設備。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT3 (Default Level)",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "OT3_Low_Cold": {
                    "sop_id": "en50155_2017_ot3_low",
                    "name": "OT3 低溫冷測：-25°C，16h（非通電）【預設等級】",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT3 預設等級低溫。-25°C 持續 16 小時。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT3 (Default Level)",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
                "OT3_ST1_High": {
                    "sop_id": "en50155_2017_ot3_st1",
                    "name": "OT3 + ST1 開機延伸：+85°C，10 分鐘（OT3+15°C）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "ST1 為預設開機延伸溫度等級（OTx+15°C，持續 10 分鐘）。模擬設備在高溫環境下剛開機時的短暫溫度峰值。ST1/ST2 不適用 OT5/OT6。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 0.17,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 2 ST1 (OT3+15°C, 10 min)",
                    "steps": [
                        {
                            "step_id": 1,
                            "name": "設備開機與預檢",
                            "description": "確認電源、保險絲、水箱水位正常。",
                            "requires_photo": True,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 2,
                            "name": "升溫至 OT3+15°C = +85°C",
                            "description": "通電狀態，升溫至 85°C，速率 1°C/min。確認設備在升溫過程中功能正常。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 3,
                            "name": "維持 85°C，10 分鐘",
                            "description": "通電狀態維持 +85°C 恰好 10 分鐘（±1 分鐘），監控設備功能是否正常。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 4,
                            "name": "測試完成確認",
                            "description": "10 分鐘後確認設備無異常，拍照記錄。",
                            "requires_photo": True,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 5,
                            "name": "儲存測試紀錄",
                            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                    ],
                },
                "OT4_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot4_high",
                    "name": "OT4 高溫乾熱：+70°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT4 等級：高溫同 OT3（+70°C），但低溫更嚴苛（-40°C），適用於寒帶地區車外設備。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT4",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "OT4_High_Operating": {
                    "sop_id": "en50155_2017_ot4_high_operating",
                    "name": "OT4 高溫通電測試：+70°C，2h/電壓步驟，三段電壓（通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT4 高溫通電功能測試（Continuous Operation Checks）。通電狀態，70°C 下依序執行三段電壓：下限×0.7 → 額定 → 上限×1.25，每段停留 2 小時並確認功能正常。升降溫含在總測試時間內，法規參考總時間約 8 小時。對應 SOP 方法驗證報告 Method III（EN 50155:2017）。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Clause 13.4.5 OT4 + IEC 60068-2-2 Test Bb",
                    "steps": [
                        {
                            "step_id": 1,
                            "name": "升溫至 70°C，確認穩定",
                            "description": "通電狀態，升溫至 70°C，速率 1°C/min。確認溫度穩定在 70°C ± 2°C。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 2,
                            "name": "電壓段 1：下限 ×0.7，2 小時",
                            "description": "將電源調整至產品額定電壓下限 ×0.7，維持 70°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 3,
                            "name": "電壓段 2：額定電壓，2 小時",
                            "description": "將電源調整至產品額定操作電壓，維持 70°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 4,
                            "name": "電壓段 3：上限 ×1.25，2 小時",
                            "description": "將電源調整至產品額定電壓上限 ×1.25，維持 70°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 5,
                            "name": "測試完成，拍照記錄",
                            "description": "三段電壓全部完成，拍照記錄設備狀態與最終溫度讀值。",
                            "requires_photo": True,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 6,
                            "name": "儲存測試紀錄",
                            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫，下載 CSV 測試報告。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                    ],
                },
                "OT4_High_Operating_ST1": {
                    "sop_id": "en50155_2017_ot4_high_operating_st1",
                    "name": "OT4 + ST1 高溫通電測試：+85°C，2h/電壓步驟，三段電壓（通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT4 ST1 延伸高溫通電功能測試（OT4+15°C = 85°C）。通電狀態，85°C 下依序執行三段電壓：下限×0.7 → 額定 → 上限×1.25，每段停留 2 小時。模擬設備在高溫開機狀態下的嚴苛通電條件。法規參考總時間約 8 小時。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Clause 13.4.5 OT4 + Table 2 ST1 (OT4+15°C)",
                    "steps": [
                        {
                            "step_id": 1,
                            "name": "升溫至 85°C，確認穩定",
                            "description": "通電狀態，升溫至 85°C（OT4+15°C），速率 1°C/min。確認溫度穩定在 85°C ± 2°C。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 2,
                            "name": "電壓段 1：下限 ×0.7，2 小時",
                            "description": "將電源調整至產品額定電壓下限 ×0.7，維持 85°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 3,
                            "name": "電壓段 2：額定電壓，2 小時",
                            "description": "將電源調整至產品額定操作電壓，維持 85°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 4,
                            "name": "電壓段 3：上限 ×1.25，2 小時",
                            "description": "將電源調整至產品額定電壓上限 ×1.25，維持 85°C，通電運作 2 小時。確認設備功能正常，記錄電壓值。",
                            "requires_photo": False,
                            "requires_parameters": True,
                            "optional": False,
                        },
                        {
                            "step_id": 5,
                            "name": "測試完成，拍照記錄",
                            "description": "三段電壓全部完成，拍照記錄設備狀態與最終溫度讀值。",
                            "requires_photo": True,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 6,
                            "name": "儲存測試紀錄",
                            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫，下載 CSV 測試報告。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                    ],
                },
                "OT4_Low_Cold": {
                    "sop_id": "en50155_2017_ot4_low",
                    "name": "OT4 低溫冷測：-40°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT4 等級低溫。-40°C 持續 16 小時，適用於北歐/俄羅斯等極寒地區鐵路。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT4",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "OT5_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot5_high",
                    "name": "OT5 高溫乾熱：+85°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT5 等級：適用於半導體驅動單元(SDU)、引擎控制等高溫設備，高溫 +85°C。ST1/ST2 不適用。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT5",
                    "steps": steps_single_temp(85.0, 16, "high"),
                },
                "OT5_Low_Cold": {
                    "sop_id": "en50155_2017_ot5_low",
                    "name": "OT5 低溫冷測：-40°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT5 等級低溫。-40°C 持續 16 小時，非通電。ST1/ST2 不適用。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT5",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "OT6_High_Dry_Heat": {
                    "sop_id": "en50155_2017_ot6_high",
                    "name": "OT6 高溫乾熱：+85°C，16h（非通電）【最嚴苛】",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT6 最嚴苛等級：高溫 +85°C，低溫 -40°C。適用於車外極端環境設備。ST1/ST2 不適用。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT6",
                    "steps": steps_single_temp(85.0, 16, "high"),
                },
                "OT6_Low_Cold": {
                    "sop_id": "en50155_2017_ot6_low",
                    "name": "OT6 低溫冷測：-40°C，16h（非通電）【最嚴苛】",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "OT6 最嚴苛等級低溫。-40°C 持續 16 小時。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Table 1 OT6",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "Rapid_Temp_Variation": {
                    "sop_id": "en50155_2017_rtv",
                    "name": "快速溫度變化測試（隧道模擬）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "EN 50155:2017 新增。模擬列車進出隧道的快速溫度變化（含結露風險），速率 ≥20°C/min。",
                    "high_temperature": 70.0,
                    "low_temperature": -25.0,
                    "target_temperature": 70.0,
                    "ramp_rate": 20.0,  # ✅ 法規明文：≥20°C/min
                    "dwell_time_hours": 0.25,
                    "cycles": 3,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 Clause 4.3.4 Rapid Temperature Variation",
                    "steps": steps_cycle(-25.0, 70.0, 3),
                },
                "Cyclic_Damp_Heat": {
                    "sop_id": "en50155_2017_damp",
                    "name": "濕熱循環測試：25°C ↔ 55°C，93%RH，2 循環（2017 強制）",
                    "test_type": "chamber",
                    "version": "EN 50155:2017",
                    "description": "EN 50155:2017 版起為強制測試項目（2007版為可選）。依 IEC 60068-2-30 Test Db 執行，評估結露對設備的影響。",
                    "high_temperature": 55.0,
                    "low_temperature": 25.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 2.0,  # ⚠️ IEC 60068-2-30 程序控制（3h升溫），非獨立速率
                    "dwell_time_hours": 12,
                    "cycles": 2,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2017 + IEC 60068-2-30 Test Db",
                    "steps": steps_cycle(25.0, 55.0, 2, 93.0),
                },
            },
        },
        "EN 50155:2007": {
            "label": "EN 50155:2007（舊版，T1/T2/T3/TX）",
            "description": "舊版四溫度類別（T1/T2/T3/TX），現有客戶仍使用。2017版已廢止並取代此版本。",
            "tests": {
                "T1_High_+55": {
                    "sop_id": "en50155_2007_t1_high",
                    "name": "T1 高溫乾熱：+55°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2007",
                    "description": "舊版 T1 等級，高溫上限 +55°C，低溫 -25°C。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2007 Clause 12.2.4 T1",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "T2_High_+70": {
                    "sop_id": "en50155_2007_t2_high",
                    "name": "T2 高溫乾熱：+70°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2007",
                    "description": "舊版 T2 等級，高溫上限 +70°C，低溫 -25°C。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2007 Clause 12.2.4 T2",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "T3_High_+85": {
                    "sop_id": "en50155_2007_t3_high",
                    "name": "T3 高溫乾熱：+85°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2007",
                    "description": "舊版 T3 等級，高溫上限 +85°C，低溫 -40°C。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2007 Clause 12.2.4 T3",
                    "steps": steps_single_temp(85.0, 16, "high"),
                },
                "TX_Low_-40": {
                    "sop_id": "en50155_2007_tx_low",
                    "name": "TX 低溫儲存：-40°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "EN 50155:2007",
                    "description": "舊版 TX 等級低溫，-40°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "EN 50155:2007 Clause 12.2.4 TX",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
            },
        },
    },
}
