"""
IEC 60068 基礎環境測試標準
- IEC 60068-2-1:2007  (Test A: Cold) — Ab 低溫儲存 / Ad 低溫工作
- IEC 60068-2-2:2007  (Test B: Dry Heat) — Ba 高溫儲存 / Bb 高溫工作
- IEC 60068-2-14:2023 (Test N: Temp Change) — Na 熱衝擊 / Nb 漸進循環
- IEC 60068-2-30:2005 (Test Db: Damp Heat Cyclic)
- IEC 60068-2-78:2012 (Test Cab: Damp Heat Steady State)

ramp_rate：
  ✅ 標溫（-25°C 等級）：1°C/min
  ✅ 寬溫（-40°C 及以下）：3°C/min
  ⚠️ Ba/Bb 高溫：暫用 3.0°C/min，待確認
  ✅ Nb：法規允許 1~15°C/min，慣用 2°C/min
  ✅ Na：轉換 <30 秒，設 30.0（非速率概念）
  ⚠️ Db：IEC 60068-2-30 程序控制（3h 升溫），非獨立速率，暫用 2.0
  ✅ Cab：1°C/min
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "IEC 60068 基礎環境測試",
    "description": "IEC 60068 為所有環境測試之基礎標準，分多個 Part 涵蓋各種應力條件。",
    "versions": {
        "IEC 60068-2-1:2007 (Test A: Cold)": {
            "label": "IEC 60068-2-1:2007 冷測試",
            "description": "低溫儲存（Test Ab）與低溫工作（Test Ad）。",
            "tests": {
                "Ab_-25_16h": {
                    "sop_id": "iec60068_ab_-25_16h",
                    "name": "低溫儲存 Test Ab：-25°C，16 小時（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-1:2007",
                    "description": "Test Ab 標溫等級：非通電狀態，-25°C 低溫儲存 16 小時，評估標溫產品耐受性",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,  # ✅ 標溫（-25°C）：
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-1:2007 Test Ab + HQ-PD.486",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
                "Ab_-40_16h": {
                    "sop_id": "iec60068_ab_-40_16h",
                    "name": "低溫儲存 Test Ab：-40°C，16 小時（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-1:2007",
                    "description": "Test Ab 寬溫等級：非通電狀態，-40°C 低溫儲存，評估寬溫產品耐受性。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 3.0,  # ✅ 寬溫（-40°C）：3°C/min（
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-1:2007 Test Ab",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "Ab_-55_16h": {
                    "sop_id": "iec60068_ab_-55_16h",
                    "name": "低溫儲存 Test Ab：-55°C，16 小時（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-1:2007",
                    "description": "Test Ab 嚴苛等級：-55°C 非通電低溫儲存。",
                    "high_temperature": None,
                    "low_temperature": -55.0,
                    "target_temperature": -55.0,
                    "ramp_rate": 3.0,  # ✅ 寬溫以上（-55°C）：3°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-1:2007 Test Ab",
                    "steps": steps_single_temp(-55.0, 16, "low"),
                },
                "Ad_-25_48h": {
                    "sop_id": "iec60068_ad_-25_48h",
                    "name": "低溫工作 Test Ad：-25°C，48 小時（通電，含 Power ON/OFF 循環）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-1:2007",
                    "description": "Test Ad 標溫工作：通電狀態，-25°C 停留 48 小時，含 10 次 Power ON/OFF 循環（5 min OFF / 2 hr ON）",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,  # ✅ 標溫（-25°C）
                    "dwell_time_hours": 48,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-1:2007 Test Ad + HQ-PD.485",
                    "steps": [
                        {
                            "step_id": 1,
                            "name": "確認降溫曲線正常",
                            "description": "監控溫度曲線，確認正在降溫至 -25°C，速率 1°C/min，無異常跳動。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 2,
                            "name": "確認達到 -25°C，開始計時",
                            "description": "確認溫度穩定在 -25°C ± 2°C，開始計時 48 小時停留。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 3,
                            "name": "執行 Power ON/OFF 循環（10 次）",
                            "description": "在 -25°C 穩定後執行 10 次開關機循環：關機 5 分鐘 → 開機 2 小時，重複 10 次。每次開機後確認設備功能正常。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 4,
                            "name": "48h 停留完成，拍照記錄",
                            "description": "確認已完成 48 小時低溫停留及全部 10 次開關機循環，拍照記錄設備狀態。",
                            "requires_photo": True,
                            "requires_parameters": False,
                            "optional": False,
                        },
                        {
                            "step_id": 5,
                            "name": "儲存測試紀錄",
                            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫，下載 CSV 測試報告。",
                            "requires_photo": False,
                            "requires_parameters": False,
                            "optional": False,
                        },
                    ],
                },
            },
        },
        "IEC 60068-2-2:2007 (Test B: Dry Heat)": {
            "label": "IEC 60068-2-2:2007 乾熱測試",
            "description": "高溫儲存（Test Ba）與高溫工作（Test Bb）。",
            "tests": {
                "Ba_+85_16h": {
                    "sop_id": "iec60068_ba_+85_16h",
                    "name": "乾熱儲存 Test Ba：+85°C，16 小時（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-2:2007",
                    "description": "Test Ba：非通電高溫儲存，評估在高溫下的材料穩定性。",
                    "high_temperature": 85.0,
                    "low_temperature": None,
                    "target_temperature": 85.0,
                    "ramp_rate": 3.0,  # ⚠️ 高溫無標溫/寬溫之分，暫用 3.0°C/min，待確認
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-2:2007 Test Ba",
                    "steps": steps_single_temp(85.0, 16, "high"),
                },
                "Ba_+125_2h": {
                    "sop_id": "iec60068_ba_+125_2h",
                    "name": "乾熱儲存 Test Ba：+125°C，2 小時（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-2:2007",
                    "description": "Test Ba 嚴苛等級：+125°C 非通電高溫儲存。",
                    "high_temperature": 125.0,
                    "low_temperature": None,
                    "target_temperature": 125.0,
                    "ramp_rate": 3.0,  # ⚠️ 暫用 3.0°C/min，待確認
                    "dwell_time_hours": 2,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-2:2007 Test Ba",
                    "steps": steps_single_temp(125.0, 2, "high"),
                },
                "Bb_+70_16h": {
                    "sop_id": "iec60068_bb_+70_16h",
                    "name": "乾熱工作 Test Bb：+70°C，16 小時（通電）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-2:2007",
                    "description": "Test Bb：通電工作狀態，評估高溫下的電氣功能性。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 3.0,  # ⚠️ 暫用 3.0°C/min，待確認
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-2:2007 Test Bb",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
            },
        },
        "IEC 60068-2-14:2023 (Test N: Temp Change)": {
            "label": "IEC 60068-2-14:2023 溫度變化測試",
            "description": "Test Na（空氣對空氣快速熱衝擊）/ Test Nb（單腔線性速率漸進式循環）。最新版 Ed.7 2023年發布。",
            "tests": {
                "Nb_-40_+85_2Cmin_5cycle": {
                    "sop_id": "iec60068_nb_-40_+85_5cycle",
                    "name": "Test Nb 漸進溫度循環：-40°C ↔ +85°C，2°C/min，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-14:2023",
                    "description": "Test Nb：單腔體線性速率升降溫，2°C/min，每端停留 2 小時，5 循環。最常用的工業標準溫度循環。",
                    "high_temperature": 85.0,
                    "low_temperature": -40.0,
                    "target_temperature": 85.0,
                    "ramp_rate": 2.0,  # ✅ 法規明文允許範圍 1~15°C/min，此為慣用值
                    "dwell_time_hours": 2,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-14:2023 Test Nb",
                    "steps": steps_cycle(-40.0, 85.0, 5),
                },
                "Nb_-25_+70_2Cmin_3cycle": {
                    "sop_id": "iec60068_nb_-25_+70_3cycle",
                    "name": "Test Nb 漸進溫度循環：-25°C ↔ +70°C，2°C/min，3 循環",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-14:2023",
                    "description": "Test Nb 溫和等級：單腔體線性速率升降溫，每端停留 2 小時，適用於辦公室/工業溫帶環境設備。",
                    "high_temperature": 70.0,
                    "low_temperature": -25.0,
                    "target_temperature": 70.0,
                    "ramp_rate": 2.0,  # ✅ 法規明文允許範圍 1~15°C/min，此為慣用值
                    "dwell_time_hours": 2,
                    "cycles": 3,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-14:2023 Test Nb",
                    "steps": steps_cycle(-25.0, 70.0, 3),
                },
                "Na_-55_+125_5cycle": {
                    "sop_id": "iec60068_na_-55_+125_5cycle",
                    "name": "Test Na 熱衝擊：-55°C ↔ +125°C，轉換 < 30 秒，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-14:2023",
                    "description": "Test Na：空氣對空氣雙腔體熱衝擊，快速轉換（<30秒），每端停留 30 分鐘，測試焊點/材料熱衝擊耐受性。",
                    "high_temperature": 125.0,
                    "low_temperature": -55.0,
                    "target_temperature": 125.0,
                    "ramp_rate": 30.0,  # ✅ 法規明文：轉換 <30 秒，非線性速率概念
                    "dwell_time_hours": 0.5,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-14:2023 Test Na",
                    "steps": steps_cycle(-55.0, 125.0, 5),
                },
                "Na_-40_+85_5cycle": {
                    "sop_id": "iec60068_na_-40_+85_5cycle",
                    "name": "Test Na 熱衝擊：-40°C ↔ +85°C，轉換 < 30 秒，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-14:2023",
                    "description": "Test Na 常用等級：空氣對空氣雙腔體快速熱衝擊，適用於一般工業電子設備。",
                    "high_temperature": 85.0,
                    "low_temperature": -40.0,
                    "target_temperature": 85.0,
                    "ramp_rate": 30.0,  # ✅ 法規明文：轉換 <30 秒，非線性速率概念
                    "dwell_time_hours": 0.5,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-14:2023 Test Na",
                    "steps": steps_cycle(-40.0, 85.0, 5),
                },
            },
        },
        "IEC 60068-2-30:2005 (Test Db: Damp Heat Cyclic)": {
            "label": "IEC 60068-2-30:2005 濕熱循環測試",
            "description": "Test Db 交變濕熱循環：25°C↔55°C，95%RH。專門評估結露情況下的腐蝕耐受性。",
            "tests": {
                "Db_25_55_95RH_6cycle": {
                    "sop_id": "iec60068_db_25_55_6cycle",
                    "name": "濕熱循環 Test Db：25°C ↔ 55°C，95%RH，6 循環（每循環 24h）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-30:2005",
                    "description": "Test Db：交變濕熱循環，測試結露冷凝對材料、塗層、密封的影響。每循環 24 小時，高溫 12h + 降溫 3~6h + 室溫。",
                    "high_temperature": 55.0,
                    "low_temperature": 25.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 2.0,  # ⚠️ IEC 60068-2-30 為程序控制（3h升溫），非獨立速率
                    "dwell_time_hours": 12,
                    "cycles": 6,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-30:2005 Test Db",
                    "steps": steps_cycle(25.0, 55.0, 6, 95.0),
                },
                "Db_25_40_93RH_2cycle": {
                    "sop_id": "iec60068_db_25_40_2cycle",
                    "name": "濕熱循環 Test Db Variant 1：25°C ↔ 40°C，93%RH，2 循環",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-30:2005",
                    "description": "Test Db 輕度等級（Variant 1）：40°C/93%RH，適用於辦公室/室內設備，2 循環。",
                    "high_temperature": 40.0,
                    "low_temperature": 25.0,
                    "target_temperature": 40.0,
                    "ramp_rate": 2.0,  # ⚠️ IEC 60068-2-30 為程序控制（3h升溫），非獨立速率
                    "dwell_time_hours": 12,
                    "cycles": 2,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-30:2005 Test Db Variant 1",
                    "steps": steps_cycle(25.0, 40.0, 2, 93.0),
                },
            },
        },
        "IEC 60068-2-78:2012 (Test Cab: Damp Heat Steady State)": {
            "label": "IEC 60068-2-78:2012 穩態高溫高濕測試",
            "description": "Test Cab：穩態高溫高濕，評估產品在持續高溫高濕環境下的功能性與材料耐受性。測試溫度為產品額定最高工作溫度 + 5°C，通電工作狀態。",
            "tests": {
                "Cab_65_16h_95RH": {
                    "sop_id": "iec60068_cab_65_16h_95rh",
                    "name": "穩態高溫高濕 Test Cab：65°C，16h，95%RH（標溫，Method I）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-78:2012",
                    "description": "Test Cab Method I：標溫產品（額定最高工作溫度 + 5°C = 65°C），95%RH，16 小時穩態高溫高濕，通電。",
                    "high_temperature": 65.0,
                    "low_temperature": None,
                    "target_temperature": 65.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-78:2012 Test Cab Method I",
                    "steps": steps_single_temp(65.0, 16, "high"),
                },
                "Cab_65_24h_95RH": {
                    "sop_id": "iec60068_cab_65_24h_95rh",
                    "name": "穩態高溫高濕 Test Cab：65°C，24h，95%RH（標溫，Method II）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-78:2012",
                    "description": "Test Cab Method II：標溫產品（額定最高工作溫度 + 5°C = 65°C），95%RH，24 小時穩態高溫高濕，通電。",
                    "high_temperature": 65.0,
                    "low_temperature": None,
                    "target_temperature": 65.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 24,
                    "cycles": 1,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-78:2012 Test Cab Method II",
                    "steps": steps_single_temp(65.0, 24, "high"),
                },
                "Cab_90_16h_95RH": {
                    "sop_id": "iec60068_cab_90_16h_95rh",
                    "name": "穩態高溫高濕 Test Cab：90°C，16h，95%RH（寬溫，Method I）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-78:2012",
                    "description": "Test Cab Method I：寬溫產品（額定最高工作溫度 + 5°C = 90°C），95%RH，16 小時穩態高溫高濕，通電。",
                    "high_temperature": 90.0,
                    "low_temperature": None,
                    "target_temperature": 90.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-78:2012 Test Cab Method I",
                    "steps": steps_single_temp(90.0, 16, "high"),
                },
                "Cab_90_24h_95RH": {
                    "sop_id": "iec60068_cab_90_24h_95rh",
                    "name": "穩態高溫高濕 Test Cab：90°C，24h，95%RH（寬溫，Method II）",
                    "test_type": "chamber",
                    "version": "IEC 60068-2-78:2012",
                    "description": "Test Cab Method II：寬溫產品（額定最高工作溫度 + 5°C = 90°C），95%RH，24 小時穩態高溫高濕，通電。",
                    "high_temperature": 90.0,
                    "low_temperature": None,
                    "target_temperature": 90.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 24,
                    "cycles": 1,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 3.0,
                    "reference": "IEC 60068-2-78:2012 Test Cab Method II",
                    "steps": steps_single_temp(90.0, 24, "high"),
                },
            },
        },
    },
}
