"""
IEC 61850-3 變電站通訊自動化設備標準
- Ed.2:2013（現行，Class C1/C2/C3）
- Ed.1:2002（舊版）

ramp_rate：✅1°C/min
  - C3 Cold（-40°C 寬溫）：3°C/min
  - Ed.1 Cold（-40°C 寬溫）：3°C/min
  - Cab 高溫高濕：1°C/min

冷測分類說明：
  - Operational（通電，Test Ad）
  - Storage（非通電，Test Ab）

高溫高濕說明（IEC 61850-3 Ed.2 Method III）：
  - 固定條件：40°C / 93%RH / 240h（法規明文規定，非產品規格決定）
  - C1/C2/C3 共用相同參數（法規未依 Class 分級）
"""

from ._base import steps_single_temp, steps_cycle

TREE = {
    "label": "IEC 61850-3 變電站通訊自動化設備",
    "description": "適用於電力廠站與變電站的 IED 通訊設備。環境測試依 IEC 60068 系列執行。",
    "versions": {
        "IEC 61850-3 Ed.2:2013": {
            "label": "IEC 61850-3 Ed.2:2013（現行版）",
            "description": "Ed.2 對應 IEC 60255-27。定義 Class C1（標準室內）、C2（戶外箱體）、C3（嚴苛環境）三個安裝位置等級。",
            "tests": {
                "C1_Dry_Heat_+55": {
                    "sop_id": "iec61850_ed2_c1_high",
                    "name": "Class C1 乾熱：+55°C，16h（室內標準環境，通電）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級：標準室內變電站（有空調），工作溫度 -10°C ~ +55°C，依 IEC 60068-2-2 Test Bb 執行，通電。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-2 Test Be",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "C1_Cold_-10_Storage": {
                    "sop_id": "iec61850_ed2_c1_low_storage",
                    "name": "Class C1 冷測（儲存）：-10°C，16h（非通電，Test Ab）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級低溫儲存（Test Ab）。-10°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -10.0,
                    "target_temperature": -10.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-1 Test Ab",
                    "steps": steps_single_temp(-10.0, 16, "low"),
                },
                "C1_Damp_Heat": {
                    "sop_id": "iec61850_ed2_c1_damp",
                    "name": "Class C1 濕熱循環：25°C ↔ 55°C，95%RH，6 循環",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級濕熱。依 IEC 60068-2-30 Test Db 執行，6 循環，95%RH。",
                    "high_temperature": 55.0,
                    "low_temperature": 25.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 2.0,  # ⚠️ IEC 60068-2-30 程序控制
                    "dwell_time_hours": 12,
                    "cycles": 6,
                    "humidity_rh_percent": 95.0,
                    "humidity_control": True,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-30",
                    "steps": steps_cycle(25.0, 55.0, 6, 95.0),
                },
                "C1_Cab_40_240h_93RH": {
                    "sop_id": "iec61850_ed2_c1_cab",
                    "name": "Class C1 高溫高濕 Test Cab：40°C，240h，93%RH（Method III）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級穩態高溫高濕（Method III）。依 IEC 60068-2-78 Test Cab 執行。40°C / 93%RH / 240 小時，法規明文固定條件，通電工作狀態。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 240,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 + IEC 60068-2-78 Test Cab Method III",
                    "steps": steps_single_temp(40.0, 240, "high"),
                },
                "C1_Cab_High_NonOp_16h": {
                    "sop_id": "iec61850_ed2_c1_cab_nonop",
                    "name": "Class C1 高溫 Test Cab：55°C，16h，Non-Operating（Method V）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級高溫非通電測試（Method V）。依 IEC 60068-2-78 Test Cab 執行，55°C / 16h，非通電。",
                    "high_temperature": 55.0,
                    "low_temperature": None,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-78 Test Cab Method V",
                    "steps": steps_single_temp(55.0, 16, "high"),
                },
                "C1_Nb_-10_+55_5cycle": {
                    "sop_id": "iec61850_ed2_c1_nb",
                    "name": "Class C1 溫度循環 Test Nb：-10°C ↔ +55°C，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C1 等級溫度循環。Test Nb 單腔線性速率，-10°C ↔ +55°C，每端停留 3 小時，5 循環，1°C/min。",
                    "high_temperature": 55.0,
                    "low_temperature": -10.0,
                    "target_temperature": 55.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 3,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-14 Test Nb",
                    "steps": steps_cycle(-10.0, 55.0, 5),
                },
                "C2_Dry_Heat_+70": {
                    "sop_id": "iec61850_ed2_c2_high",
                    "name": "Class C2 乾熱：+70°C，16h（戶外箱體，通電）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級：戶外箱體或無空調室內，工作溫度 -25°C ~ +70°C。通電工作狀態（Test Bb）。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-2 Test Be",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "C2_Cold_-25_Operational": {
                    "sop_id": "iec61850_ed2_c2_low_operational",
                    "name": "Class C2 冷測（工作）：-25°C，16h（通電，Test Ad）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級低溫工作（Test Ad）。-25°C 持續 16 小時，通電狀態。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-1 Test Ad",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
                "C2_Cold_-25_Storage": {
                    "sop_id": "iec61850_ed2_c2_low_storage",
                    "name": "Class C2 冷測（儲存）：-25°C，16h（非通電，Test Ab）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級低溫儲存（Test Ab）。-25°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -25.0,
                    "target_temperature": -25.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-1 Test Ab",
                    "steps": steps_single_temp(-25.0, 16, "low"),
                },
                "C2_Cab_40_240h_93RH": {
                    "sop_id": "iec61850_ed2_c2_cab",
                    "name": "Class C2 高溫高濕 Test Cab：40°C，240h，93%RH（Method III）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級穩態高溫高濕（Method III）。依 IEC 60068-2-78 Test Cab 執行。40°C / 93%RH / 240 小時，法規明文固定條件，通電工作狀態。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 240,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 + IEC 60068-2-78 Test Cab Method III",
                    "steps": steps_single_temp(40.0, 240, "high"),
                },
                "C2_Cab_High_NonOp_16h": {
                    "sop_id": "iec61850_ed2_c2_cab_nonop",
                    "name": "Class C2 高溫 Test Cab：70°C，16h，Non-Operating（Method V）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級高溫非通電測試（Method V）。依 IEC 60068-2-78 Test Cab 執行，70°C / 16h，非通電。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-78 Test Cab Method V",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "C2_Nb_-40_+70_5cycle": {
                    "sop_id": "iec61850_ed2_c2_nb",
                    "name": "Class C2 溫度循環 Test Nb：-40°C ↔ +70°C，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C2 等級溫度循環。Test Nb 單腔線性速率，-40°C ↔ +70°C，每端停留 3 小時，5 循環，1°C/min。",
                    "high_temperature": 70.0,
                    "low_temperature": -40.0,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 3,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-14 Test Nb",
                    "steps": steps_cycle(-40.0, 70.0, 5),
                },
                "C3_Dry_Heat_+70": {
                    "sop_id": "iec61850_ed2_c3_high",
                    "name": "Class C3 乾熱：+70°C，16h（嚴苛戶外環境，通電）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C3 等級：嚴苛戶外環境，工作溫度 -40°C ~ +70°C。最嚴苛安裝位置等級，通電工作狀態。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-2 Test Be",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "C3_Cold_-40_Storage": {
                    "sop_id": "iec61850_ed2_c3_low_storage",
                    "name": "Class C3 冷測（儲存）：-40°C，16h（非通電，Test Ab）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C3 等級低溫儲存（Test Ab）。-40°C 持續 16 小時，非通電，最嚴苛低溫儲存要求。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 3.0,  # ✅ 寬溫（-40°C）：3°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-1 Test Ab",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
                "C3_Cab_40_240h_93RH": {
                    "sop_id": "iec61850_ed2_c3_cab",
                    "name": "Class C3 高溫高濕 Test Cab：40°C，240h，93%RH（Method III）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C3 等級穩態高溫高濕（Method III）。依 IEC 60068-2-78 Test Cab 執行。40°C / 93%RH / 240 小時，法規明文固定條件，通電工作狀態。",
                    "high_temperature": 40.0,
                    "low_temperature": None,
                    "target_temperature": 40.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 240,
                    "cycles": 1,
                    "humidity_rh_percent": 93.0,
                    "humidity_control": True,
                    "power_on": True,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 + IEC 60068-2-78 Test Cab Method III",
                    "steps": steps_single_temp(40.0, 240, "high"),
                },
                "C3_Cab_High_NonOp_16h": {
                    "sop_id": "iec61850_ed2_c3_cab_nonop",
                    "name": "Class C3 高溫 Test Cab：70°C，16h，Non-Operating（Method V）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C3 等級高溫非通電測試（Method V）。依 IEC 60068-2-78 Test Cab 執行，70°C / 16h，非通電。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-78 Test Cab Method V",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "C3_Nb_-40_+70_5cycle": {
                    "sop_id": "iec61850_ed2_c3_nb",
                    "name": "Class C3 溫度循環 Test Nb：-40°C ↔ +70°C，5 循環",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.2:2013",
                    "description": "C3 等級溫度循環。Test Nb 單腔線性速率，-40°C ↔ +70°C，每端停留 3 小時，5 循環，1°C/min。",
                    "high_temperature": 70.0,
                    "low_temperature": -40.0,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,
                    "dwell_time_hours": 3,
                    "cycles": 5,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-14 Test Nb",
                    "steps": steps_cycle(-40.0, 70.0, 5),
                },
            },
        },
        "IEC 61850-3 Ed.1:2002": {
            "label": "IEC 61850-3 Ed.1:2002（舊版）",
            "description": "初版，單一環境條件規範，未細分 Class C1/C2/C3。",
            "tests": {
                "Dry_Heat_+70": {
                    "sop_id": "iec61850_ed1_high",
                    "name": "Ed.1 高溫乾熱：+70°C，16h",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.1:2002",
                    "description": "Ed.1 標準高溫測試，+70°C 持續 16 小時。",
                    "high_temperature": 70.0,
                    "low_temperature": None,
                    "target_temperature": 70.0,
                    "ramp_rate": 1.0,  # ✅ 1°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2002 Ed.1",
                    "steps": steps_single_temp(70.0, 16, "high"),
                },
                "Cold_-40": {
                    "sop_id": "iec61850_ed1_low",
                    "name": "Ed.1 低溫冷測：-40°C，16h（非通電）",
                    "test_type": "chamber",
                    "version": "IEC 61850-3 Ed.1:2002",
                    "description": "Ed.1 標準低溫測試，-40°C 持續 16 小時，非通電。",
                    "high_temperature": None,
                    "low_temperature": -40.0,
                    "target_temperature": -40.0,
                    "ramp_rate": 3.0,  # ✅ 寬溫（-40°C）：3°C/min
                    "dwell_time_hours": 16,
                    "cycles": 1,
                    "humidity_rh_percent": None,
                    "humidity_control": False,
                    "power_on": False,
                    "temp_tolerance": 2.0,
                    "humi_tolerance": 5.0,
                    "reference": "IEC 61850-3:2002 Ed.1",
                    "steps": steps_single_temp(-40.0, 16, "low"),
                },
            },
        },
    },
}
